In [53]:
import pandas as pd
import requests

url = "https://apisidra.ibge.gov.br/values/t/7060/n1/all/v/63/p/all/c315/all?formato=json"
r = requests.get(url)
data = r.json()

df = pd.DataFrame(data[1:])  # pula o cabeçalho
df.head()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N,D4C,D4N
0,1,Brasil,2,%,0.21,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7169,Índice geral
1,1,Brasil,2,%,0.39,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7170,1.Alimentação e bebidas
2,1,Brasil,2,%,0.20,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7171,11.Alimentação no domicílio
3,1,Brasil,2,%,0.75,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7172,"1101.Cereais, leguminosas e oleaginosas"
4,1,Brasil,2,%,1.31,1,Brasil,63,IPCA - Variação mensal,202001,janeiro 2020,7173,1101002.Arroz

In [55]:
url = "https://apisidra.ibge.gov.br/values/t/1737/n1/all/v/all/p/all?formato=json"
df = pd.DataFrame(requests.get(url).json()[1:])
#df.head()
df[["MC","MN","D2C","D2N"]].drop_duplicates()

,MC,MN,D2C,D2N
0,30,Número-índice,2266,IPCA - Número-índice (base: dezembro de 1993 =...
559,,,63,IPCA - Variação mensal
560,2,%,63,IPCA - Variação mensal
1118,,,2263,IPCA - Variação acumulada em 3 meses
1121,2,%,2263,IPCA - Variação acumulada em 3 meses
1677,,,2264,IPCA - Variação acumulada em 6 meses
1683,2,%,2264,IPCA - Variação acumulada em 6 meses
2236,,,69,IPCA - Variação acumulada no ano
2237,2,%,69,IPCA - Variação acumulada no ano
2795,,,2265,IPCA - Variação acumulada em 12 meses
2807,2,%,2265,IPCA - Variação acumulada em 12 meses

In [56]:
import requests
import pandas as pd

url = "https://apisidra.ibge.gov.br/values/t/1737/n1/1/v/2266/p/all?formato=json"
df = pd.DataFrame(requests.get(url).json()[1:])
df.head()

,NC,NN,MC,MN,V,D1C,D1N,D2C,D2N,D3C,D3N
0,1,Brasil,30,Número-índice,0.0000000076183,1,Brasil,2266,IPCA - Número-índice (base: dezembro de 1993 =...,197912,dezembro 1979
1,1,Brasil,30,Número-índice,0.0000000081223,1,Brasil,2266,IPCA - Número-índice (base: dezembro de 1993 =...,198001,janeiro 1980
2,1,Brasil,30,Número-índice,0.0000000084973,1,Brasil,2266,IPCA - Número-índice (base: dezembro de 1993 =...,198002,fevereiro 1980
3,1,Brasil,30,Número-índice,0.0000000090104,1,Brasil,2266,IPCA - Número-índice (base: dezembro de 1993 =...,198003,março 1980
4,1,Brasil,30,Número-índice,0.0000000094867,1,Brasil,2266,IPCA - Número-índice (base: dezembro de 1993 =...,198004,abril 1980

In [36]:
df[['D4C', 'D4N']].drop_duplicates().sort_values('D4C')

        D4C                          D4N
85   101448         1107097.Capa de filé
102  101466     1108072.Peixe - curimatã
381  101642   6301004.Produto para barba
382  101644    6301006.Produto para pele
17   107608  1102029.Massa semipreparada
..      ...                          ...
447    7787               91.Comunicação
448    7788             9101.Comunicação
449    7789              9101001.Correio
454    7794  9101019.Aparelho telefônico
108    8874        1108096.Peixe - peroá

[457 rows x 2 columns]

In [44]:
url_2 = "https://apisidra.ibge.gov.br/values/t/7060/n1/all/v/all/p/202001?formato=json"
df_2 = pd.DataFrame(requests.get(url_2).json()[1:])
df_2[['D2C','D2N']].drop_duplicates()

    D2C                                    D2N
0    63                 IPCA - Variação mensal
1    69       IPCA - Variação acumulada no ano
2  2265  IPCA - Variação acumulada em 12 meses
3    66                     IPCA - Peso mensal

In [34]:
df.groupby('D4N')['D4C'].unique()

D4N
1.Alimentação e bebidas                                       [7170]
11.Alimentação no domicílio                                   [7171]
1101.Cereais, leguminosas e oleaginosas                       [7172]
1101002.Arroz                                                 [7173]
1101051.Feijão - mulatinho                                    [7175]
                                                              ...
9101018.Acesso à internet                                   [107688]
9101019.Aparelho telefônico                                   [7794]
9101115.Serviços de streaming                                [47671]
9101116.Combo de telefonia, internet e tv por assinatura     [47672]
Índice geral                                                  [7169]
Name: D4C, Length: 457, dtype: object